/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AgeGroup = { 'sevenEight' : null } |
  { 'nineTen' : null } |
  { 'fiveSix' : null };
export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface GameResult {
  'total' : bigint,
  'timeSpent' : bigint,
  'difficulty' : Difficulty,
  'correct' : bigint,
  'gameType' : GameType,
  'ageGroup' : AgeGroup,
}
export type GameType = { 'subtraction' : null } |
  { 'division' : null } |
  { 'addition' : null } |
  { 'multiplication' : null };
export interface PracticeUpdate {
  'correct' : bigint,
  'timeBonus' : [] | [bigint],
  'incorrect' : bigint,
  'starsEarned' : [] | [bigint],
  'currentStreak' : bigint,
}
export interface ProgressSummary {
  'attempts' : bigint,
  'history' : Array<GameResult>,
  'score' : bigint,
  'stars' : bigint,
}
export interface TimesTableSummary {
  'timeSpent' : bigint,
  'totalQuestions' : bigint,
  'starsEarned' : bigint,
  'tableSpeed' : Array<[bigint, bigint]>,
  'tableCorrect' : bigint,
}
export interface UserProfile {
  'name' : string,
  'preferredAgeGroup' : [] | [AgeGroup],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEarnedReward' : ActorMethod<[Difficulty, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletedLevels' : ActorMethod<[Difficulty], [] | [bigint]>,
  'getEarnedRewards' : ActorMethod<[Difficulty], [] | [Array<string>]>,
  'getProgressSummary' : ActorMethod<[], Array<ProgressSummary>>,
  'getTimesTableSummary' : ActorMethod<[], [] | [TimesTableSummary]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStats' : ActorMethod<[Principal], [bigint, bigint]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordLevelCompletion' : ActorMethod<[Difficulty, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitResult' : ActorMethod<
    [GameType, AgeGroup, bigint, bigint, bigint, Difficulty],
    undefined
  >,
  'updatePracticeStats' : ActorMethod<[bigint, bigint, bigint], PracticeUpdate>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];