/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AgeGroup = IDL.Variant({
  'sevenEight' : IDL.Null,
  'nineTen' : IDL.Null,
  'fiveSix' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'preferredAgeGroup' : IDL.Opt(AgeGroup),
});
export const GameType = IDL.Variant({
  'subtraction' : IDL.Null,
  'division' : IDL.Null,
  'addition' : IDL.Null,
  'multiplication' : IDL.Null,
});
export const GameResult = IDL.Record({
  'total' : IDL.Nat,
  'timeSpent' : IDL.Nat,
  'difficulty' : Difficulty,
  'correct' : IDL.Nat,
  'gameType' : GameType,
  'ageGroup' : AgeGroup,
});
export const ProgressSummary = IDL.Record({
  'attempts' : IDL.Nat,
  'history' : IDL.Vec(GameResult),
  'score' : IDL.Nat,
  'stars' : IDL.Nat,
});
export const TimesTableSummary = IDL.Record({
  'timeSpent' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'starsEarned' : IDL.Nat,
  'tableSpeed' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  'tableCorrect' : IDL.Nat,
});
export const PracticeUpdate = IDL.Record({
  'correct' : IDL.Nat,
  'timeBonus' : IDL.Opt(IDL.Nat),
  'incorrect' : IDL.Nat,
  'starsEarned' : IDL.Opt(IDL.Nat),
  'currentStreak' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEarnedReward' : IDL.Func([Difficulty, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletedLevels' : IDL.Func([Difficulty], [IDL.Opt(IDL.Int)], ['query']),
  'getEarnedRewards' : IDL.Func(
      [Difficulty],
      [IDL.Opt(IDL.Vec(IDL.Text))],
      ['query'],
    ),
  'getProgressSummary' : IDL.Func([], [IDL.Vec(ProgressSummary)], ['query']),
  'getTimesTableSummary' : IDL.Func([], [IDL.Opt(TimesTableSummary)], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStats' : IDL.Func([IDL.Principal], [IDL.Nat, IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordLevelCompletion' : IDL.Func([Difficulty, IDL.Int], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitResult' : IDL.Func(
      [GameType, AgeGroup, IDL.Nat, IDL.Nat, IDL.Nat, Difficulty],
      [],
      [],
    ),
  'updatePracticeStats' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [PracticeUpdate],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AgeGroup = IDL.Variant({
    'sevenEight' : IDL.Null,
    'nineTen' : IDL.Null,
    'fiveSix' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'preferredAgeGroup' : IDL.Opt(AgeGroup),
  });
  const GameType = IDL.Variant({
    'subtraction' : IDL.Null,
    'division' : IDL.Null,
    'addition' : IDL.Null,
    'multiplication' : IDL.Null,
  });
  const GameResult = IDL.Record({
    'total' : IDL.Nat,
    'timeSpent' : IDL.Nat,
    'difficulty' : Difficulty,
    'correct' : IDL.Nat,
    'gameType' : GameType,
    'ageGroup' : AgeGroup,
  });
  const ProgressSummary = IDL.Record({
    'attempts' : IDL.Nat,
    'history' : IDL.Vec(GameResult),
    'score' : IDL.Nat,
    'stars' : IDL.Nat,
  });
  const TimesTableSummary = IDL.Record({
    'timeSpent' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'starsEarned' : IDL.Nat,
    'tableSpeed' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
    'tableCorrect' : IDL.Nat,
  });
  const PracticeUpdate = IDL.Record({
    'correct' : IDL.Nat,
    'timeBonus' : IDL.Opt(IDL.Nat),
    'incorrect' : IDL.Nat,
    'starsEarned' : IDL.Opt(IDL.Nat),
    'currentStreak' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEarnedReward' : IDL.Func([Difficulty, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletedLevels' : IDL.Func(
        [Difficulty],
        [IDL.Opt(IDL.Int)],
        ['query'],
      ),
    'getEarnedRewards' : IDL.Func(
        [Difficulty],
        [IDL.Opt(IDL.Vec(IDL.Text))],
        ['query'],
      ),
    'getProgressSummary' : IDL.Func([], [IDL.Vec(ProgressSummary)], ['query']),
    'getTimesTableSummary' : IDL.Func([], [IDL.Opt(TimesTableSummary)], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStats' : IDL.Func([IDL.Principal], [IDL.Nat, IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordLevelCompletion' : IDL.Func([Difficulty, IDL.Int], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitResult' : IDL.Func(
        [GameType, AgeGroup, IDL.Nat, IDL.Nat, IDL.Nat, Difficulty],
        [],
        [],
      ),
    'updatePracticeStats' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [PracticeUpdate],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };